config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'homepage#index'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :show, :create, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :groups_users
  has_many :users, through: :groups_users

  validates :name, :date, :price_cap, presence: true

end

app/models/groups_user.rb
class GroupsUser < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :accepted, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true

  has_many :items_users
  has_many :users, through: :items_users
end

app/models/items_user.rb
class ItemsUser < ApplicationRecord
  belongs_to :user
  belongs_to :items_user

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :first_name, :last_name, :email, :username, presence: true
  validates :email, :username, uniqueness: true
  validates :password, length: {minimum: 6}
  validates_confirmation_of :password

  has_many :groups_users
  has_many :groups, through: :groups_users

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token
//
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user != nil
  end

  def authenticate_user
    if !current_user
      redirect_to signin_path, notice: "You must be signed in to do that!"
    end
  end

  helper_method :current_user, :authenticate_user
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])

    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: "You have successfully logged in!"
    else
      @errors = ["Invalid email and/or password"]
      render 'new'
    end
  end

  def destroy
    session[:user_id] = @current_user = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user= current_user
    if !@user
      redirect_to "/"
    end
  end

  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to "/users/#{@user.id}"
    else
      @errors = @user.errors.full_messages
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homepage/index.html.erb
<h1>Homepage</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gift Swap</title>
    <%= csrf_meta_tags %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="row">
      <nav class="navbar bg-primary">
        <div class="container-fluid">
          <div class="navbar-header">
            <a href="/">Home</a>
          </div>
          <ul class="nav navbar-nav">
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li><%= link_to "Logout", session_path(current_user), method: :delete %></li>

            <% else %>
              <li><%= link_to "Register", new_user_path %></li>
              <li><%= link_to "Log In", new_session_path %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </div>
    <div class="container-fluid" id="main">
      <%= yield %>
    </div>

    <div class="footer">
      <div class="container">
        <p>&copy;Gift Swap


        </p>

      </div>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @errors %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@errors.count, "error") %>.
    </div>
    <ul class="error_messages">
    <% @errors.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<form id="register-form" method="post" action="/users">
  <div class="reg-header">
    <h2>Register</h2>
  </div>
  <%= render 'shared/error_messages' %>
  <div class="container">
    <label id="reg-label"><b>First Name</b></label>
    <input id="reg-first-name" type="text" placeholder="Enter First Name" name="user[first_name]" required>

    <label id="reg-label"><b>Last Name</b></label>
    <input id="reg-last-name" type="text" placeholder="Enter Last Name" name="user[last_name]" required>

    <label id="reg-label"><b>Username</b></label>
    <input id="reg-username" type="text" placeholder="Enter Username" name="user[username]" required>

    <label id="reg-label"><b>Email</b></label>
    <input id="reg-email" type="email" placeholder="Enter Email" name="user[email]" required>

    <label id="reg-label"><b>Password</b></label>
    <input id="reg-password" type="password" placeholder="Enter Password" name="user[password]" required>

    <label id="reg-label"><b>Password Confirmation</b></label>
    <input id="reg-password-confirmation" type="password" placeholder="Enter Password Confirmation" name="user[password_confirmation]" required>

    <button id="reg-button" type="submit">Sign Up</button>
  </div>
</form>

app/views/users/show.html.erb
<h1>User Page</h1>

<h3><%=@user.username %></h3>